"""The `--verify` gate compares the committed file against the code.

It exists because the committed file was once generated by an older revision of
its own script and every test stayed green. The gate then went red at random: it
was an exact match, it ran in CI, and it failed on a commit that touched neither
the experiment nor the file. Two runs of the same code differed by one ULP on the
raw losses and by twenty orders of magnitude on the annealed ones, because
annealing the gate's temperature to 0.05 saturates the sigmoid.

So the comparison is tested directly, against hand-made payloads, rather than by
re-running a two-minute experiment. What has to hold:

* the last ULP between platforms is absorbed;
* a real drift -- the stale-file failure the gate exists for -- is not;
* a change in *shape* is not either;
* and the annealed rows, which are not reproducible, are still checked for the
  claim they carry.
"""

from __future__ import annotations

import copy
import importlib.util
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]


def _learned_gate():
    spec = importlib.util.spec_from_file_location(
        "learned_gate_for_tests", ROOT / "experiments" / "learned_gate.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


learned_gate = _learned_gate()
_COMMITTED = json.loads((ROOT / "learned-gate.json").read_text())


def _scrub(obj):
    if isinstance(obj, dict):
        return {k: _scrub(v) for k, v in obj.items() if k != "wall_seconds"}
    if isinstance(obj, list):
        return [_scrub(x) for x in obj]
    return obj


def _scrubbed() -> dict:
    return _scrub(_COMMITTED)


def test_an_identical_payload_verifies() -> None:
    assert learned_gate.differ(_scrubbed(), _scrubbed()) == []
    assert learned_gate.annealed_problems(_scrubbed()) == []


def test_a_one_ulp_difference_is_absorbed() -> None:
    """What the 3.11 runner actually differed by on the raw rows.

    `14.443256952904889` against `14.443256952904886` is the whole drift on those
    fields, and a gate that fails on it is a gate that fails on nothing.
    """
    fresh = _scrubbed()
    fresh["training_reports"][1]["final_state_loss"] = float(
        fresh["training_reports"][1]["final_state_loss"].hex() and
        _nextafter(fresh["training_reports"][1]["final_state_loss"]))
    assert learned_gate.differ(_scrubbed(), fresh) == []


def _nextafter(value: float) -> float:
    import math

    return math.nextafter(value, math.inf)


def test_a_real_drift_is_not_absorbed() -> None:
    """The failure the gate exists for: a file from an older revision."""
    for factor in (1.01, 2.0):
        fresh = _scrubbed()
        fresh["training_reports"][0]["final_loss"] *= factor
        assert learned_gate.differ(_scrubbed(), fresh), factor

    fresh = _scrubbed()
    fresh["conditions"]["learned_gate_trained_raw"]["spread"]["mean"] = 0.99
    assert learned_gate.differ(_scrubbed(), fresh)

    fresh = _scrubbed()
    fresh["soft_gate_cost"]["trained_raw"]["mean_hold_multiplier"] = 1.0
    assert learned_gate.differ(_scrubbed(), fresh)


def test_a_change_in_shape_is_not_absorbed() -> None:
    fresh = _scrubbed()
    del fresh["sharpness"]
    assert learned_gate.differ(_scrubbed(), fresh)

    fresh = _scrubbed()
    fresh["held_out_keys"]["conditions"]["key"]["extra"] = 1
    assert learned_gate.differ(_scrubbed(), fresh)

    fresh = _scrubbed()
    fresh["training_reports"] = fresh["training_reports"][:-1]
    assert learned_gate.differ(_scrubbed(), fresh)


def test_the_annealed_rows_are_checked_for_their_claim() -> None:
    """They are not reproducible, but the conclusion they support is checked.

    The README's reading is that annealing reaches less than training soft and
    thresholding. If that stopped holding, the row would still be in the table
    and would no longer mean anything.
    """
    stable = _scrubbed()
    assert learned_gate.annealed_problems(stable) == []

    broken = copy.deepcopy(stable)
    broken["conditions"]["learned_gate_trained_annealed"]["spread"]["mean"] = 1.0
    problems = learned_gate.annealed_problems(broken)
    assert problems and "not below" in problems[0], problems

    diverged = copy.deepcopy(stable)
    for report in diverged["training_reports"]:
        if report.get("anneal_to"):
            report["final_loss"] = float("nan")
    problems = learned_gate.annealed_problems(diverged)
    assert any("final_loss" in p for p in problems), problems


def test_the_annealed_rows_are_excluded_from_the_exact_comparison() -> None:
    """Which is the point: their values cannot be compared, so they are not.

    A gate that fails on the twenty-orders-of-magnitude difference between two
    runs of the same code is not measuring the code. The values are blanked and
    the keys are kept, and the same rows are still checked for their claim.
    """
    fresh = copy.deepcopy(_COMMITTED)
    for report in fresh["training_reports"]:
        if report.get("anneal_to"):
            report["final_loss"] = 1234.5678
            report["final_state_loss"] = 0.0
    fresh["conditions"]["learned_gate_trained_annealed"]["spread"]["mean"] = 0.9
    fresh = _scrub(fresh)

    assert learned_gate.differ(learned_gate.normalise(_scrubbed()),
                               learned_gate.normalise(fresh)) == []

    # A key removed from one of those rows is still a difference: only the
    # values are allowed to move.
    missing = copy.deepcopy(fresh)
    del missing["training_reports"][-1]["final_loss"]
    assert learned_gate.differ(learned_gate.normalise(_scrubbed()),
                               learned_gate.normalise(missing))

    # ...and the same rows are still checked for their claim.
    broken = _scrub(copy.deepcopy(fresh))
    broken["conditions"]["learned_gate_trained_annealed"]["spread"]["mean"] = 1.0
    assert learned_gate.annealed_problems(broken)

    # A changed anneal temperature is a difference, not a blanked value.
    retuned = copy.deepcopy(fresh)
    for report in retuned["training_reports"]:
        if report.get("anneal_to"):
            report["anneal_to"] = 0.5
    assert learned_gate.differ(learned_gate.normalise(_scrubbed()),
                               learned_gate.normalise(_scrub(retuned)))
